### ISSUE TITLE
All configured authentication methods failed

### ISSUE THREAD

**Issue by verbes4** [dominictoms/sshbot#1]
I understand that this is almost certainly not being worked on anymore, however whenever I try to run any command it seems the bot has trouble connecting with SSH. 

```
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: All configured authentication methods failed
    at doNextAuth (/home/mmmmmm/Documents/sshbot/node_modules/ssh2/lib/client.js:865:21)
    at tryNextAuth (/home/mmmmmm/Documents/sshbot/node_modules/ssh2/lib/client.js:1082:7)
    at USERAUTH_FAILURE (/home/mmmmmm/Documents/sshbot/node_modules/ssh2/lib/client.js:430:11)
    at 51 (/home/mmmmmm/Documents/sshbot/node_modules/ssh2/lib/protocol/handlers.misc.js:408:16)
    at Protocol.onPayload (/home/mmmmmm/Documents/sshbot/node_modules/ssh2/lib/protocol/Protocol.js:2052:10)
    at AESGCMDecipherBinding.decrypt (/home/mmmmmm/Documents/sshbot/node_modules/ssh2/lib/protocol/crypto.js:1086:26)
    at Protocol.parsePacket [as _parse] (/home/mmmmmm/Documents/sshbot/node_modules/ssh2/lib/protocol/Protocol.js:2021:25)
    at Protocol.parse (/home/mmmmmm/Documents/sshbot/node_modules/ssh2/lib/protocol/Protocol.js:306:16)
    at Socket.<anonymous> (/home/mmmmmm/Documents/sshbot/node_modules/ssh2/lib/client.js:775:21)
    at Socket.emit (node:events:514:28)
Emitted 'error' event on Client instance at:
    at Socket.<anonymous> (/home/mmmmmm/Documents/sshbot/node_modules/ssh2/lib/client.js:777:20)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  level: 'client-authentication'
}


```

**Comment by domtoms** [comment]
Is everything set up with the .env file correctly? If that's all set up properly then perhaps the machine you're trying to ssh into requires something the bot doesn't support.

**Comment by verbes4** [comment]
Heres my .env file, with Discord key removed. I am running it on a Raspberry Pi 3B, Raspbian 11.
![Screenshot_20231211_154639](https://github.com/dominictoms/sshbot/assets/24574201/b20492e1-0e45-4bc2-9506-b0ec2c6e4dc3)

**Comment by domtoms** [comment]
Are you trying to run the bot on the same machine you're trying to ssh into? Also just making sure the ssh key is in the same directory as the envfile.

**Comment by verbes4** [comment]
I am, not sure if that would be an issue or not. Heres the contents of the folder
![Screenshot_20231211_155232](https://github.com/dominictoms/sshbot/assets/24574201/fd15b5dc-b951-4f6b-b931-d0433355dcd3)

**Comment by domtoms** [comment]
Yeah that looks perfect! If it's not an issue with the IP address then I'm afraid I'm not really sure what it could be, this bot was just a fun project I wrote in a few days and not something that's been well tested or maintained.
